version: '3.9'
services:
  engine:
    container_name: exodus
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      HOST_IP_ADDR: ${HOST_IP_ADDR}
    ports:
      - '5000:8000' # foo
      - '5001:8001' # bar
      - '5002:8002' # baz
    depends_on:
      - rabbitmq
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      # AMQP protocol port
      - '5672:5672'
      # Management UI
      - '15672:15672'
